### ISSUE TITLE
Setting value to >= 2

### ISSUE THREAD

**Issue by Katniss99** [gogoair/react-combo-search#1]
Hi, is there a way to set the value entered at the search input to be >= 2, currently it is set at >= 3?

I tried to use the validateCallback to call my callback but it still pop up message that said that my data input is not >= 3.

Thanks.
Regards

**Comment by bojant987** [comment]
Hey, sorry for late response.
Is it possible that you misspelled validationCallback to validateCallback?
You also need to send inputErrorMessage, the default is "This field is required and should be at least 3 characters long"
ie. `validationCallback={value => value >=2} `
and `inputErrorMessage="Enter at least 2 characters please"`

**Comment by Katniss99** [comment]
Thanks.
